// <auto-generated />
using System;
using CmsSync.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CmsSync.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CmsWriteDbContext))]
    [Migration("20260802142305_InitialCmsPersistence")]
    partial class InitialCmsPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CmsSync.Infrastructure.Persistence.Models.CmsDeletionTombstone", b =>
                {
                    b.Property<string>("EntityId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("DeletedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("LastDeleteEventKey")
                        .HasMaxLength(209)
                        .HasColumnType("nvarchar(209)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<long>("LastDeletedGeneration")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetime2(7)");

                    b.HasKey("EntityId");

                    b.ToTable("CmsDeletionTombstones", null, t =>
                        {
                            t.HasCheckConstraint("CK_CmsDeletionTombstones_Generation_NonNegative", "[LastDeletedGeneration] >= 0");
                        });
                });

            modelBuilder.Entity("CmsSync.Infrastructure.Persistence.Models.CmsEntity", b =>
                {
                    b.Property<string>("EntityId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<bool>("AdministrativeDisabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AdministrativeStateChangedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("AdministrativeStateChangedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("CmsPublicationStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("CurrentVersionOccurredAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("EntityEventHighWatermarkUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetime2(7)");

                    b.Property<long>("Generation")
                        .HasColumnType("bigint");

                    b.Property<long>("LatestVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("binary(32)")
                        .IsFixedLength();

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetime2(7)");

                    b.HasKey("EntityId");

                    b.ToTable("CmsEntities", null, t =>
                        {
                            t.HasCheckConstraint("CK_CmsEntities_AdministrativeAudit", "([AdministrativeStateChangedAtUtc] IS NULL AND [AdministrativeStateChangedBy] IS NULL) OR ([AdministrativeStateChangedAtUtc] IS NOT NULL AND [AdministrativeStateChangedBy] IS NOT NULL)");

                            t.HasCheckConstraint("CK_CmsEntities_EventTimestamps", "[EntityEventHighWatermarkUtc] >= [CurrentVersionOccurredAtUtc]");

                            t.HasCheckConstraint("CK_CmsEntities_Generation_Positive", "[Generation] > 0");

                            t.HasCheckConstraint("CK_CmsEntities_LatestVersion_Positive", "[LatestVersion] > 0");

                            t.HasCheckConstraint("CK_CmsEntities_Payload_JsonObject", "ISJSON([Payload], OBJECT) = 1");

                            t.HasCheckConstraint("CK_CmsEntities_PublicationStatus", "[CmsPublicationStatus] IN ('Published', 'Unpublished')");
                        });
                });

            modelBuilder.Entity("CmsSync.Infrastructure.Persistence.Models.CmsEntityRevision", b =>
                {
                    b.Property<string>("EntityId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<long>("Generation")
                        .HasColumnType("bigint");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FirstObservedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("FirstObservedPayload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("binary(32)")
                        .IsFixedLength();

                    b.HasKey("EntityId", "Generation", "Version");

                    b.ToTable("CmsEntityRevisions", null, t =>
                        {
                            t.HasCheckConstraint("CK_CmsEntityRevisions_Generation_Positive", "[Generation] > 0");

                            t.HasCheckConstraint("CK_CmsEntityRevisions_Payload_JsonObject", "ISJSON([FirstObservedPayload], OBJECT) = 1");

                            t.HasCheckConstraint("CK_CmsEntityRevisions_Version_Positive", "[Version] > 0");
                        });
                });

            modelBuilder.Entity("CmsSync.Infrastructure.Persistence.Models.CmsEventProcessingLog", b =>
                {
                    b.Property<long>("ProcessingLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProcessingLogId"));

                    b.Property<string>("AuthenticatedCmsSubject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("EntityId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<byte[]>("EventContentHash")
                        .HasMaxLength(32)
                        .HasColumnType("binary(32)")
                        .IsFixedLength();

                    b.Property<DateTime?>("EventOccurredAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("EventType")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("ExternalEventId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<long?>("Generation")
                        .HasColumnType("bigint");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(209)
                        .HasColumnType("nvarchar(209)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<bool>("OwnsIdempotencyKey")
                        .HasColumnType("bit");

                    b.Property<byte[]>("PayloadHash")
                        .HasMaxLength(32)
                        .HasColumnType("binary(32)")
                        .IsFixedLength();

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetime2(7)");

                    b.Property<long?>("ReplayOfProcessingLogId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ResultingVersion")
                        .HasColumnType("bigint");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<long?>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("ProcessingLogId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_CmsEventProcessingLogs_IdempotencyOwner")
                        .HasFilter("[OwnsIdempotencyKey] = CAST(1 AS bit) AND [IdempotencyKey] IS NOT NULL");

                    b.HasIndex("ReplayOfProcessingLogId");

                    b.HasIndex("BatchId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("UX_CmsEventProcessingLogs_BatchId_Sequence");

                    b.ToTable("CmsEventProcessingLogs", null, t =>
                        {
                            t.HasCheckConstraint("CK_CmsEventProcessingLogs_EventType", "[EventType] IS NULL OR [EventType] IN ('publish', 'unpublish', 'delete')");

                            t.HasCheckConstraint("CK_CmsEventProcessingLogs_Generation_NonNegative", "[Generation] IS NULL OR [Generation] >= 0");

                            t.HasCheckConstraint("CK_CmsEventProcessingLogs_IdempotencyOwner", "[OwnsIdempotencyKey] = 0 OR [IdempotencyKey] IS NOT NULL");

                            t.HasCheckConstraint("CK_CmsEventProcessingLogs_Outcome", "[Outcome] IN ('Applied', 'Duplicate', 'Equivalent', 'Stale', 'Invalid', 'Conflict')");

                            t.HasCheckConstraint("CK_CmsEventProcessingLogs_ReplayDoesNotOwnIdentity", "[ReplayOfProcessingLogId] IS NULL OR [OwnsIdempotencyKey] = 0");

                            t.HasCheckConstraint("CK_CmsEventProcessingLogs_ResultingVersion_Positive", "[ResultingVersion] IS NULL OR [ResultingVersion] > 0");

                            t.HasCheckConstraint("CK_CmsEventProcessingLogs_Sequence_NonNegative", "[Sequence] >= 0");

                            t.HasCheckConstraint("CK_CmsEventProcessingLogs_Version_Positive", "[Version] IS NULL OR [Version] > 0");
                        });
                });

            modelBuilder.Entity("CmsSync.Infrastructure.Persistence.Models.CmsEventProcessingLog", b =>
                {
                    b.HasOne("CmsSync.Infrastructure.Persistence.Models.CmsEventProcessingLog", null)
                        .WithMany()
                        .HasForeignKey("ReplayOfProcessingLogId")
                        .OnDelete(DeleteBehavior.NoAction);
                });
#pragma warning restore 612, 618
        }
    }
}
